---
title: "Data Sources"
output: 
  html_document:
    toc: true
    toc_float: true
---

Information about the data sources we used in our analyses are documented here.

## Rat sightings data:
This data was taken from the NYC Open Data website, adapted from a data set from 311 requests. The rat sightings were filtered out from the requests before the csv was imported to R. The data and time variables and location variables like longitude, latitude, and borough were kept. Observations were filtered to rat sightings between January 1, 2016 and October 31, 2023.

## Weather data:
The data source used for this component of the analysis is from the National Oceanic and Atmospheric Administration (NOAA). Variables include data, precipitation, minimum temperature, and maximum temperature. The data was filtered to only include years 2017-2022 for New York City, and then merged by date with the rat sightings data.


## Trash data:
The data source used for the trash vs. rat sighting analysis is NYC Open Data for both rat sightings and trash tonnage data. The trash tonnage data provides monthly collection tonnages that the NYC Department of Sanitation collects from NYC residences and institutions. Variables included `year`, `month`, `borough`, `refusetonscollected` (tons of trash or refuse collected), `papertonscollected` (tons of source-separated recyclable paper collected), and `mgptonscollected` (tons of source-separated recyclable metal, glass, plastic, and beverage cartons collected). The analyses describe the change in total tons of trash by borough, rat count by total tons of trash and borough, and tons of trash by rat count and trash type.

## Restaurant inspection data:
The data source used for the restaurant component of the rat sighting analysis is NYC Open Data. The New York City Department of Health and Mental Hygiene Restaurant Inspection Results provides daily updates on inspections of currently active restaurants. Variables include `Year`, `boro`, `violation_code`, and others. The data was filtered to specifically look at "04" violations, specifically "04K", evidence of rats, and were analyzed across year, borough, and cuisine type.

## Socioeconomic factor data:
The data source utilized for this component of the rat sightings analysis is from the U.S. Census Bureau. Variables associated with crowdingl, vacancy, education, and poverty were dowloaded from the site at the census tract level for the entire state of New York. The data was then filtered to only included counties that are a part of New York City (Bronx, Queens, Richmond, Kings, and New York), and then analyzed alongside the distribution of rat sightings across these counties.
