---
title: "Final Project Report"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---
This report gives an overview of our project process, results, and thoughts.

## [Motivation and Related Work](intro.html)
When brainstorming for this project, our group members found ourselves drawn towards understanding NYC rats. Since rats are likely related to various other determinants of health, as Mailman students who study, live, or work in New York City, we were interested in figuring out the scope of the problem.

News reports about rats in NYC, laws passed about rodent mitigation, trending articles about rat spottings, and more inspired us to go ahead with this topic.

## Initial Questions
Since we were interested in the scope of the rat problem, our initial questions were:

* How big is the NYC rat problem?
* Has the coronation of the Rat Czar done anything for the rodent population?
* How has the rat problem changed over the past few years?

As we tided and joined data, we realized the Rat Czar is so new that there isn't much information about her statutes yet. So new questions arose:

* How are rat sightings related to other conditions in NYC?
* Specifically, how might sociodemographic factors, weather conditions, trash density, and restaurant inspections be related to rat sightings?
* What does the Rat Czar need to focus on to win the war against rats?

## Data

Data was taken majorly from [NYC Open Data](https://opendata.cityofnewyork.us/), [Census data](https://www.census.gov/data.html), and [NOAA](https://www.ncei.noaa.gov/cdo-web/datasets).

Data was either imported from csv or scraped from the web, tidied with the usual `dplyr` functions, and joined by variables like `r # need to fill this in - probably stuff like county, year, month, etc, but need to check Rmds`

More information about the data sources are found [here](data_sources.html) and the data cleaning process is documented [here](data_overview.html).

## [Analyses](visualization.html)
As stated earlier, the questions we had for our project evolved as we worked to join and analyze data. Here are some select summaries and visualizations of our data (more can be found in the analyses subsections). 

```{r}
# Note- will need to put the data cleaning code here as well and make sure the file paths are all correct

# general rat sighting data

#rat sighting data by sociodemographic variables

#weather

# trash

# restaurants
```


## Discussion
After all of our hard work, we have decided that...
