---
title: "Data Visualization"
output: 
  html_document:
    toc: true
    toc_float: true
---

Below are highlights of our analyses and include what we believe to be our most important data plots:

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(plotly)
library(lubridate)
library(dplyr)
```

```{r rat sightings}
sightings = read_csv('data/NYC_Rat_Sightings.csv') |>
  janitor::clean_names() |>
  separate(created_date, into=c("month","e", "day","f", "year", "g", "time"), sep=c(2,3,5,6,10,11)) |>
  select(-e,-f,-g) |>
  mutate(date = paste(year, month, day, sep=""),
         date = as.numeric(date)) |> 
  filter(date <= 20231031,
         date >= 20160101,
         !incident_zip <= 10000,
         !incident_zip > 11697,
         !borough %in% c("Unspecified", NA)) |>
  select(-agency, -agency_name, -complaint_type, -descriptor, -landmark, -facility_type, -park_facility_name, -vehicle_type, -taxi_company_borough, -taxi_pick_up_location, -bridge_highway_name, -road_ramp, -bridge_highway_segment, -bridge_highway_direction) |> select(unique_key, date, year, month, day, everything())
```

```{r}
weather_df = rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2016-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

```{r}
sightings$date <- as.Date(as.character(sightings$date), format = "%Y%m%d")

rat_weather =
  right_join(sightings, weather_df, by="date")
```

Overall rat sightings trends:
```{r}
rat_weather |>
  mutate(year = as.factor(year)) |>
  group_by(date) |>
  summarize(count = n(), year) |>  
  ggplot(aes(x = date, y = count, color=year)) +
  geom_point(alpha = 0.25) + 
  labs(title = "Time Series: Rat Sightings Over Time",
       x = "Date",
       y = "Number of Rat Sightings")
```

```{r}
# total count per year by borough - most in brooklyn and manhattan
sightings |> 
  group_by(year, borough) |> 
  summarize(count=n()) |> 
  plot_ly(x=~year, y=~count, color=~borough, type="scatter", mode="line")
```

Rat sightings & Weather
```{r}
rat_weather |>
  group_by(date) |>
  summarize(count = n(), year, tmax) |>
  ggplot(aes(x = tmax, y = count, color = year)) + 
  geom_point(alpha = .3) +
  geom_smooth(se = FALSE, color="black") + 
  facet_grid(. ~ year) +
  labs(title = "Maximum Temperature vs. Rat Sightings by Year",
       x = "Maximum temperature (degrees Celsius)",
       y = "Number of Rat Sightings")
```

Rat sightings & Trash


Rat sightings & Restaurants

```{r inspections_df}
#Importing NYC Restaurant Inspections csv
inspections_df = read_csv("./data/NYC_Restaurant_Inspections.csv") |>
  janitor::clean_names() |>
  separate(inspection_date, c("Month", "Day", "Year"), sep = "/") |>
  select(-Day) |> #can remove other columns as needed
  filter(as.numeric(Year) > 2015)
```

```{r violation plot trend}
#Observations of violations
violations_plot_df <- inspections_df |>
  group_by(Year, boro, violation_code) |>
  mutate(code_obs = n())
```

```{r top 20 cuisine 04k violations}
#Plotting 04K violations by cuisine type
violations_plot_df |>
  filter(violation_code == "04K") |>
  group_by(cuisine_description) |>
  mutate(cuisine_obs = n()) |>
  filter(cuisine_obs > 25) |>
  ggplot(aes(x = reorder(cuisine_description, cuisine_obs), 
             y = cuisine_obs)) +
  geom_point(aes(color = cuisine_description)) +
  theme(axis.text.x = element_text(angle = 40, hjust = 1)) +
  labs(title = "Top 20 Rat Violation Offenders by Cuisine Type 2016-2023") +
  theme(legend.position = 'none') +
  xlab("Cuisine Type") +
  ylab("Number of Rat Violations") +
  scale_y_continuous(breaks = c(50, 100, 150, 200, 250, 300))
```

Rat sightings & SES factors






